### ISSUE TITLE
Package unpublished?

### ISSUE THREAD

**Issue by lubien** [digitalmoksha/markdown-it-inject-linenumbers#1]
![image](https://user-images.githubusercontent.com/9121359/58521375-eba24780-8192-11e9-9648-3b89008ddc93.png)

**Comment by digitalmoksha** [comment]
@lubien ridiculous how long it took me to finally publish this.  Thanks for opening the issue.

https://www.npmjs.com/package/markdown-it-inject-linenumbers

**Comment by lubien** [comment]
Congratulations! Thanks for your work
